/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.mycompany.chatapppart1;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import org.json.JSONObject;
/**
 * Messages class: represents a single chat message in the application
 * Handles message creation, validation, hashing, sending, printing
 * storing messages in a JSON file
 * @author lcebi
 */
public class Messages {
 
        // Variable Instances when creating messages
        private String messageID; // 10-digit randomly generated ID
        private int messageNumber; // position in the send loop
        private String recipientCell; // validated international cell number
        private String messageText; // max 250 characters
        private String messageHash; // autogenerated from ID + number + words
        private String sendStatus; // Status of the message (Sent, Stored, or Disregarded)
    
        // An array list that stores all messages while command is running
        private static ArrayList<Messages> messagesList = new ArrayList<>();
        
        // POE Required Arrays
        private static ArrayList<String> sentMessages = new ArrayList<>();
        private static ArrayList<String> disregardedMessages = new ArrayList<>();
        private static ArrayList<String> storedMessages = new ArrayList<>();
        private static ArrayList<String> messageHashes = new ArrayList<>();
        private static ArrayList<String> messageIDs = new ArrayList<>();

        /**
         * Constructor used to create a new message object.
         *
         * @param messageNumber is the number of the message
         * @param recipientCell is the recipients cellphone number
         * @param messageText is the message text entered by the user
         */
       // Constructor for messages
        public Messages(int messageNumber, String recipientCell, String messageText) {
            
            
        this.messageID = generateMessageID();
        this.messageNumber = messageNumber;
        this.recipientCell = recipientCell;
        this.messageText = messageText;
        this.messageHash = createMessageHash();
        
        // Default status
        this.sendStatus = "Pending";
        
        
        }
        
        
        // Generating a RandomMessage ID
        private String generateMessageID() {
        
        Random random = new Random();
        
        // Using StringBuilder to build the ID from scratch
        StringBuilder id = new StringBuilder();
        
         // Loop each number 10 times to create a 10-digit ID
         for (int i = 0; i < 10; i++) {
             
            // Add random number from 0-9 
            id.append(random.nextInt(10));
            
        }
         
         return id.toString();
         
    }
        // Check Message ID
        public boolean checkMessageID() {
        
            // Shown as true if the ID is 10 characters or less
            return messageID.length() <= 10;
         
    }
        // Check Recipient Cell
        
        /**
         * Validates the recipient cellphone number
         * The number must:
         * - Start with an international code (+)
         * - Not exceed 12 characters
         *
         * @return success or failure message
         */
        public String checkRecipientCell() {
        
           
           // Create Login object to reuse validation method
           LogIn login = new LogIn();
    
           if (login.checkCellPhoneNumber(recipientCell)) { //Reusing Login Validation from Part 1
            return "Cell phone number successfully captured.";
            
            } else {
            
            return "Cell phone number incorrectly formatted or does not contain international code. Please correct the number and try again.";
            
        }
            
    } 
        
        /**
        * Checks if the message text is within 250 characters.
        *
        * @return validation message
        */
        
        public String checkMessageLength() {
            
            // Checks if message is valid if its under 250 words
            if (messageText.length() <= 250) {
                
                return "Message ready to send.";
            } else {
                
                // Calculates the characters over character limit
                int over = messageText.length() - 250;
                
                return "Message exceeds 250 characters by " + over + ", please reduce the size.";
            }
        }
        
        
        // Create Message Hash
        
        /**
         * Creates and returns the message hash
         * Format for Hash:
         * First 2 digits of ID : message number : first word + last word in message
         *
         * Example:
         * 12:1:HELLO
         *
         * @return generated message hash
         */
        public String createMessageHash() {
        
           
            String idPart = messageID.substring(0, 2);  // The first 2 digits of message ID
            
            String[] words = messageText.split(" "); // Split message into words
             
            String firstWord =
            words[0].replaceAll("[^a-zA-Z]", ""); // The First word
            
            String lastWord =
            words[words.length - 1].replaceAll("[^a-zA-Z]", ""); // Get last word and convert to uppercase
            
            String hash = idPart + ":" + messageNumber + ":" + firstWord + lastWord; // Step 4: Build hash
            
            return hash.toUpperCase();  // Build and return hash
    }
        
        // Sent Messages
        
        /**
         * Allows the user to send, store, or disregard a message.
         * @param option user's choice
         * @return status message
         */
        public String sentMessage(String option) {
                
            // Convert user choice to lowercase
            switch (option.toLowerCase()) {
                
                case "send":
                    
                
                sendStatus = "Sent"; // Update status to sent
                
                messagesList.add(this); //Only sent messages will count
                
                // POE Arrays
                sentMessages.add(messageText);
                messageHashes.add(messageHash);
                messageIDs.add(messageID);
                
                
                return "Message successfully sent.";
                
                
                case "store":
                    
                    
                sendStatus = "Stored"; //Updates status to stored
                messagesList.add(this); //Stored messages also count
                
                messageHashes.add(messageHash);
                messageIDs.add(messageID);
            
                storeMessage();// Stores message to the JSon file
                
                return "Message successfully stored.";
                
                
                case "disregard":
                    
                    
                sendStatus = "Disregarded";//Updates status to Disregarded
                
                // POE Array
                disregardedMessages.add(messageText);
            
                return "Press 0 to delete the message.";
                
                default:
                return "Invalid option selected.";

            }
        }

        /**
         * Prints all messages stored during runtime.
         *
         * @return all messages as a formatted String
         */
        
         // Print Messages
         public static String printMessages() {
             
             // Checking if list is empty
             if (messagesList.isEmpty()) {
                 
                
                 return "No messages sent.";
             }
             
             // StringBuilder stores all output
             StringBuilder output = new StringBuilder();
            
             // Wll Loop through all stored messages
             for (Messages msg : messagesList) {
                 
                 
                 output.append("Message ID: ")
                    .append(msg.messageID)
                    .append("\n");

            output.append("Message Hash: ")
                    .append(msg.messageHash)
                    .append("\n");

            output.append("Recipient: ")
                    .append(msg.recipientCell)
                    .append("\n");

            output.append("Message: ")
                    .append(msg.messageText)
                    .append("\n");


            output.append("---------------------------------\n");
            
             }
             
             return output.toString();
             
         }   
         
         // Will Return Total Messages
         /**
         * Returns the total number of messages sent/stored.
         *
         * @return total messages in ArrayList
         */
         
         public static int returnTotalMessages() {
             
             return messagesList.size(); // Returns number of messages in ArrayList
         }
         
         /**
         * Stores message details inside a JSON file.
         *
         * JSON library used:
         * org.json
         * https://mvnrepository.com/artifact/org.json/json
         */
         
         // Store Message in JSON File
         public void storeMessage() {
        
         try {
            
             // Create JSON object
             JSONObject obj = new JSONObject();

            // Add values into JSON object
            obj.put("MessageID", messageID);
            
            obj.put("MessageNumber", messageNumber);
            
            obj.put("Recipient", recipientCell);
            
            obj.put("Message", messageText);
            
            obj.put("MessageHash", messageHash);
            
            obj.put("Status", sendStatus);
            
            FileWriter writer = new FileWriter("messages.json", true);
            
            writer.write(obj.toString());
            
            writer.write("\n");
            

            // Closes file
            writer.close();
            
            System.out.println("Message stored in JSON file.");
            
        } catch (IOException e) {
            
            System.out.println("Error writing to file: " + e.getMessage()); // Display error if file writing fails
        }

    }
    
         // ===== Part 3 Methods =====
         public static String displayStoredMessages() {
             return "Display all stored messages feature coming soon.";
             
         }
         
         public static String displayLongestMessage() {
             if (storedMessages.isEmpty()) {
                 
                 return "No stored messages available.";
                 
             }
             String longest = storedMessages.get(0);
             
             for (String message : storedMessages) {
                 
                 if (message.length() > longest.length()) {
                     
                     longest = message;
                     
                 }
             }
             
             return "Longest stored message:\n" + longest;
         }
         
         public static String searchByMessageID(String id) {
             return "Search by message ID feature coming soon.";
             
         }
         
         public static String searchByRecipient(String recipient) {
             return "Search by recipient feature coming soon.";
         }

         public static String deleteByMessageHash(String hash) {
             return "Delete by message hash feature coming soon.";
         }

         public static String displayFullReport() {
             return printMessages();
    }
    // Getters
    /**
     * Returns the generated message ID.
     *
     * @return message ID
     */
    public String getMessageID() {
         
        return messageID;
        
    }
    
    /**
     * Returns the message number.
     *
     * @return message number
     */
    public int getMessageNumber() {
        
        return messageNumber;
    }
    
    /**
     * Returns the recipient cellphone number.
     *
     * @return recipient cellphone number
     */
     public String getRecipientCell() {
         
         return recipientCell;
     }
     
      /**
     * Returns the message text.
     *
     * @return message text
     */
     public String getMessageText() {
         
         return messageText;
     }
    
     /**
     * Returns the generated message hash.
     *
     * @return message hash
     */
     public String getMessageHash() {
         
          return messageHash;
     }
    
     /**
     * Returns the message status.
     *
     * @return message status
     */
     public String getSendStatus() {
         
         return sendStatus;
     }
    
     // POE Array Getters
     public static ArrayList<String> getSentMessages() {
         
         return sentMessages;
         
     }
    
     public static ArrayList<String> getDisregardedMessages() {
         
         return disregardedMessages;
         
     }
     
     public static ArrayList<String> getStoredMessages() {
         
         return storedMessages;
         
     }
     
     public static ArrayList<String> getMessageHashes() {
         
         return messageHashes;
         
     }
     
     public static ArrayList<String> getMessageIDs() {
         
         return messageIDs;
         
     }
     
     public static void clearArrays() {
         
        sentMessages.clear();
        disregardedMessages.clear();
        storedMessages.clear();
        messageHashes.clear();
        messageIDs.clear();
        messagesList.clear();
        
     }
}
